config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/home', to: 'static_page#home'
  get '/help', to: 'static_page#help'
  get '/about', to: 'static_page#about'
  get '/contact', to: 'static_page#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/_top.html.slim
.center.jumbotron
  h1
    | Welcome to the Sample App
  h2
    | This is the home page for the
    = link_to " Ruby on Rails Tutorial ", "http://railstutorial.jp/"
    | sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'

app/views/static_page/about.html.slim
- provide :title, "About"
h1
  | About
p
  | The 
  = link_to " Ruby on Rails Tutorial ", "http://railstutorial.jp/"
  | is a
  = link_to " book ", "http://railstutorial.jp/book"
  | to teach web development with
  = link_to " Ruby on Rails.", "http://rubyonrails.org/"
  | This is the sample application for the tutorial.

app/views/static_page/contact.html.slim
- provide :title, "Contact"
h1
  | Contact
p
  | Contact the Ruby on Rails Tutorial about the sample app at the
  = link_to "contact page.", "http://railstutorial.jp/contact"

app/views/static_page/help.html.slim
- provide :title, "Help"
h1
  | Help
p
  | Get help on the Ruby on Rails Tutorial at the
  = link_to " Rails Tutorial help page ", "http://railstutorial.jp/help"
  | to get help on this sample app, see the
  = link_to " Ruby on Rails Tutorial ", "http://railstutorial.jp/book"
  | book.

app/views/static_page/home.html.slim
- if logged_in?
  = render 'shared/home_after_logged_in'
- else
  = render 'top'