config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/home', to: 'static_page#home'
  get '/help', to: 'static_page#help'
  get '/about', to: 'static_page#about'
  get '/contact', to: 'static_page#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = "The form contains #{pluralize(object.errors.count, "error")}"
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_home_after_logged_in.html.slim
.row
  aside.col-md-4
    section.user_info
      = render 'shared/user_info'
    section.stats
      = render 'shared/stats'
    section.micropost_form
      = render 'shared/micropost_form'
  .col-md-8
    h3
      | Micropost Feed
    = render 'shared/feed'

app/views/shared/_micropost_form.html.slim
= form_for @micropost do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a href="#{following_user_path(@user)}"
    strong#following.stat
      = @user.following.count
    | following
  a href="#{followers_user_path(@user)}"
    strong#followers.stat
      = @user.followers.count
    | followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1
  = current_user.name
span
  = link_to "view my profile", current_user
span
  = pluralize(current_user.microposts.count, "micropost")