config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/home', to: 'static_page#home'
  get '/help', to: 'static_page#help'
  get '/about', to: 'static_page#about'
  get '/contact', to: 'static_page#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#home'
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | The
    = link_to " Ruby on Rails Tutorial ", "http://railstutorial.jp/"
    | by
    = link_to " Michael Hartl ", "http://www.michaelhartl.com/"
  nav
    ul
      li
        = link_to "About", about_path
      li
        = link_to "Contact", contact_path
      li
        = link_to "News", "http://news.railstutorial.org/"

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home", root_path
        li
          = link_to "Help", help_path
        - if logged_in?
          li
            = link_to 'Users', users_path
          li.dropdown
            a href="#" class="dropdown-toggle" data-toggle="dropdown"
              | Account
              b.caret
            ul.dropdown-menu
              li
                = link_to "Profile", current_user
              li
                = link_to "Setting", edit_user_path(current_user)
              li.divider
              li
                = link_to "Log out", logout_path, method: "delete"
        - else
          li
            = link_to "Log in", login_path

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.slim
/! [if It IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.jp"></script>
  <![endif]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |msg_type, msg|
        = content_tag :div, msg, class: "alert alert-#{msg_type}"
      = yield
      = render 'layouts/footer'